### PR TITLE
add chatbot integration to website

### LINKED ISSUE #97: add chatbot integration to website
add chatbot integration to website

### PR DESCRIPTION
**Pull request by amanver45**
Screenshot 2024-10-29 200642
fixes #97
Screenshot 2024-10-29 200633

### CODE REVIEW

**Comment by DeadmanAbir** [comment]
> Quote reply

will check in sometime

**Comment by amanver45** [comment]
@DeadmanAbir ok

**Comment by DeadmanAbir** [comment]
> @DeadmanAbir check this and let me know if there is any issue

Not giving me answers for the components that I have in Agentgenesis!

**Comment by DeadmanAbir** [comment]
> @DeadmanAbir wait I fix it and can you give me example of question?


Uploading chatbase (1).mp4…

**Comment by amanver45** [comment]
@DeadmanAbir ok i

**Comment by DeadmanAbir** [comment]
> @DeadmanAbir i fix that issue pls check

Nice, now what I have to get in order to get the access of the chatbot? Do I have to signup on Chatbase and get my chatbot id from there?

Tell the steps so I can imitate.

**Comment by amanver45** [comment]
@DeadmanAbir where I can give you email and password

**Comment by amanver45** [comment]
@DeadmanAbir  I can share that in LinkedIn  accept my connect request in LinkedIn so i  can msg you

**Comment by amanver45** [comment]
@DeadmanAbir i fix that issue can you open it

**Comment by amanver45** [comment]
@DeadmanAbir  can yoj open it

**Comment by amanver45** [comment]
@DeadmanAbir check

**Pull request merged**
