### PR TITLE
Update Navbar and Routing: Rename 'Docs' to 'Components' and Add 'Contact Us'

### LINKED ISSUE #42: Change 'Docs' to 'Components' and Add 'Contact Us'
Description:
There are two updates needed in the Navbar component:

1.Change Heading:
- Update the Navbar heading from "Docs" to "Components".
- Update the configuration in config.js to change the route from /docs to /components.

2.Add 'Contact Us':

- Add a new menu item for "Contact Us" in the Navbar to improve user accessibility to contact information.

These changes will enhance the clarity and functionality of the Navbar, ensuring users can easily navigate to the relevant sections and access support.

Acceptance Criteria:

- The Navbar should display "Components" instead of "Docs".
- The route in config.js should be updated accordingly.
- A "Contact Us" option should be visible in the Navbar.

### PR DESCRIPTION
**Pull request by Yashhuc**
FIxes #42
**Changes:**
1. Navbar Heading Update:
* Changed the Navbar heading from "Docs" to "Components" for better clarity.
* Updated the route in config.js to change the path from /docs to /components.

2.  Add 'Contact Us' Menu Item:
* Added a new "Contact Us" item to the Navbar for easier user access to support and contact information.
* Created a new Contact Us page by adding a **contact** folder with page.jsx in the app structure.

**Files Modified:**
1. Navbar component:
* Updated the heading and added the new 'Contact Us' item.

2. Routing:
* config.js: Changed route from /docs to /components.
* components/page.jsx: Created a new page under the app folder for the Components section.
* contact/page.jsx: Added a new page for the Contact Us section to enable user interaction.

**Testing:**
1. Verified that the navigation correctly routes to /components and /contact-us.
2. Checked the Navbar for proper display of the "Components" and "Contact Us" options.

Screenshot 2024-10-10 223030

Screenshot 2024-10-10 223052

Screenshot 2024-10-10 223102

Screenshot 2024-10-10 223115

### CODE REVIEW

**Comment by DeadmanAbir** [comment]
>Fixes #42
>
> **Changes:**
> 
> 1. Navbar Heading Update:
> 
> * Changed the Navbar heading from "Docs" to "Components" for better clarity.
> * Updated the route in config.js to change the path from /docs to /components.
> 
> 2. Add 'Contact Us' Menu Item:
> 
> * Added a new "Contact Us" item to the Navbar for easier user access to support and contact information.
> * Created a new Contact Us page by adding a **contact** folder with page.jsx in the app structure.
> 
> **Files Modified:**
> 
> 1. Navbar component:
> 
> * Updated the heading and added the new 'Contact Us' item.
> 
> 2. Routing:
> 
> * config.js: Changed route from /docs to /components.
> * components/page.jsx: Created a new page under the app folder for the Components section.
> * contact/page.jsx: Added a new page for the Contact Us section to enable user interaction.
> 
> **Testing:**
> 
> 1. Verified that the navigation correctly routes to /components and /contact-us.
> 2. Checked the Navbar for proper display of the "Components" and "Contact Us" options.
> 
> Screenshot 2024-10-10 223030
> 
> Screenshot 2024-10-10 223052
> 
> Screenshot 2024-10-10 223102
> 
> Screenshot 2024-10-10 223115

**Comment by faisal004** [comment]
hi @Yashhuc Can you remove package-lock.json then push your change also for contact us i will be as simple as when anybosy cliick it will redirect to mailto:agentgenesisdev@gmail.com . We dont need a dedicated page for contact us. Thank you

**Comment by DeadmanAbir** [comment]
> hi @Yashhuc Can you remove package-lock.json then push your change also for contact us i will be as simple as when anybosy cliick it will redirect to [mailto:agentgenesisdev@gmail.com](mailto:agentgenesisdev@gmail.com) . We dont need a dedicated page for contact us. Thank you

@Yashhuc  any updates?

**Comment by Yashhuc** [comment]
> > hi @Yashhuc Can you remove package-lock.json then push your change also for contact us i will be as simple as when anybosy cliick it will redirect to [mailto:agentgenesisdev@gmail.com](mailto:agentgenesisdev@gmail.com) . We dont need a dedicated page for contact us. Thank you
> 
> @Yashhuc any updates?

Hey sorry for the delay, I have made the changes as directed and created a PR.

**Comment by Yashhuc** [comment]
Hey..! I have updated the contact-us link, and removed package-lock.json.

**Pull request merged**
