### PR TITLE
Revamp Blog Page UI for Improved User Experience

### LINKED ISSUE #58: Refactor Blog UI
#### Objective:
We aim to enhance the user experience and visual appeal of the [Agentgenesis Blog](https://agentgenesis.dev/blogs) by refactoring the UI. For this update, we'll draw inspiration from the clean and modern design of [Accertinity Blog](https://www.aceternity.com/blog). 

#### Scope:
- Refactor the blog's front-end to closely match the look and feel of Accertinity’s blog.
- Use **ShadCN UI** and **TailwindCSS** exclusively to implement the changes.
- Feel free to incorporate design elements and patterns from UI libraries such as **Accertinity UI**, **Magic UI**, etc., while maintaining consistency with the inspirational design.

#### Deliverables:
- A refined UI that improves readability, responsiveness, and overall aesthetics.
- Ensure that the new components and layouts integrate seamlessly with the existing blog structure.

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fixes #58 
This pull request implements a comprehensive redesign of the blog page UI, focusing on enhancing user engagement and readability. The new layout features an updated color scheme, streamlined navigation, and improved typography, ensuring a visually appealing and intuitive experience for users while promoting content discoverability

Screenshot 2024-11-03 at 3 11 39 AM
Hey @DeadmanAbir please review my PR.

### CODE REVIEW

**Comment by DeadmanAbir** [comment]
> This pull request implements a comprehensive redesign of the blog page UI, focusing on enhancing user engagement and readability. The new layout features an updated color scheme, streamlined navigation, and improved typography, ensuring a visually appealing and intuitive experience for users while promoting content discoverability
> 
> Screenshot 2024-11-03 at 3 11 39 AM Hey @DeadmanAbir please review my PR.



> fixes #58 This pull request implements a comprehensive redesign of the blog page UI, focusing on enhancing user engagement and readability. The new layout features an updated color scheme, streamlined navigation, and improved typography, ensuring a visually appealing and intuitive experience for users while promoting content discoverability
> 
> Screenshot 2024-11-03 at 3 11 39 AM Hey @DeadmanAbir please review my PR.

The design implmentation looks good to me, but ned two changes- 

- The featured post text breaking in mobile view, need to fix the layout or featured post.
image

- Implement the posts in such way that the first post  from `posts` array will be the featured post and then the rest posts will be shown.

**Comment by shubhagarwal1** [comment]
hey @DeadmanAbir i have understood the changes will work on. them today and submit them

**Comment by DeadmanAbir** [comment]
> hey @DeadmanAbir i have understood the changes will work on. them today and submit them

Please complete the changes so that I can merge them before time!!

**Comment by shubhagarwal1** [comment]
Hey @DeadmanAbir i have made is responsive please review the code.

**Comment by shubhagarwal1** [comment]
Screenshot 2024-11-04 at 7 57 36 PM
Screenshot 2024-11-04 at 7 59 03 PM

**Pull request merged**
